### ISSUE TITLE
Question about org mode's built-in templates

### ISSUE THREAD

**Issue by mmynsted** [GuiltyDolphin/org-evil#20]
How do I get org mode's built-in templates to work? 

See [here](https://orgmode.org/org.html#Easy-templates) 

I am not sure if this is more related to `evil-mode`, `org-evil`, my use of them, or something else.

Example:

- Open a new `org` file, perhaps `test.org`.
- From command mode, type the following where `TAB` is the tab key.

```
<sTAB
```
The code block expansion template is not executed.

     NOTE:
     Typing the same thing in insert mode, just inserts the characters.

- Exit from `Evil` mode.
- Type the following

```
<sTAB
```

The code block expansion template is executed.

**Comment by mmynsted** [comment]
Hmm this is not org-evil mode causing my issue.

**Comment by GuiltyDolphin** [comment]
@mmynsted Did you figure out what was causing the issue? Template expansion works on my end, but I'd be very interested to hear if something is conflicting with `org-evil` :)

Do you get the same behavior if you have an empty Org file, start in normal mode, then do `i<sTAB`?
