### ISSUE TITLE
Tab cycling with org-evil

### ISSUE THREAD

**Issue by recrist** [GuiltyDolphin/org-evil#22]
Hi. I just installed org-evil and immediately noticed that it changed the default tab cycling for opening and closing headers. Prior to activating org-evil, tab cycling seemed to be aware of how many sub-levels were underneath the header. For example, pressing tab on a closed header with only one layer of sub-headings would open and close with just two presses of the tab button. With org-evil active, that requires three presses of the tab key, the second of which does nothing because there is nothing to expose beneath the sub-headings. I think it would be preferable to retain the default tab cycling behavior. 

I'm using GNU Emacs 25.2.1 with Org-mode version 8.2.10 on macOS 10.14.3.

Thank you for putting together what seems otherwise a very useful package.

**Comment by GuiltyDolphin** [comment]
Hey @recrist, thanks for the feedback!

As far as I am aware (and I just had a look through the source to double check), `org-evil` doesn't directly touch the binding for `<TAB>`.

Had you been using `evil` before? Can you confirm this behaviour is not present when `org-evil` is disabled again?

If I have a simple buffer:

```
* head1
** head2
```

Then I indeed get the behaviour you are experiencing, (with everything initially closed) the first tab opens all the headings (and displays `CHILDREN` in the minibuffer), the second does apparently nothing (and displays `SUBTREE` in the minibuffer), and the third folds everything (and displays `FOLDED` in the minibuffer).

I think this might be a setting in `org`, which I don't think is being touched by `org-evil`.

Did you recently update `org`?

**Comment by recrist** [comment]
Hi. Thank you very much for getting back to me. I sincerely appreciate it. 

I think that you are correct and before I attempted to use org-evil I had updated org, which could explain the change in behavior.

However, I have just discovered that I can no longer even replicate this behavior---whether or not org-evil is enabled. 

I apologize for having raised the issue, since whatever it was it doesn't seem to have anything to do with org-evil.

Thanks again for your help.

**Comment by GuiltyDolphin** [comment]
Hey @recrist, no problem, thanks for asking :)

The binding that produces this behaviour for me is `org-cycle`, so it might be worth looking into some settings for that [this post](https://emacs.stackexchange.com/questions/32168/reverse-org-cycle) might have some more ideas on alternative configurations for this.

Hope you are able to get the behaviour you desire
