### ISSUE TITLE
Feature request: org-evil-demote to mimic org-metaright

### ISSUE THREAD

**Issue by fleimgruber** [GuiltyDolphin/org-evil#7]
org 9.0.4 from git
org-evil 20161029.222 from MELPA

`org-evil-demote` behaves like `org-shiftmetaright`, i.e. it demotes subtrees as well.  I think the default behaviour of `org-evil-demote` should be more like `org-metaright`, i.e. only demoting current heading and leave subtrees as they are.

This would make the default be less intrusive, much like `org-metaright` and `org-shiftmetaright` are chosen in regular `org-mode`.  The non-default behaviour (demoting subtrees as well) could be achieved with a two-step behaviour in the spirit of `org-evil-motion-up-heading` default `gh` binding.  What do you think?

**Comment by GuiltyDolphin** [comment]
@fleimgruber Hmm, yeah - I agree that the more common change should be on the easier key. Perhaps `g>`/`g<` or similar could be used for the sub-tree promotion/demotion, any suggestions?

**Comment by fleimgruber** [comment]
Thanks for your prompt reply.  I gave this some more thought and settled for a different approach used by https://github.com/edwtjo/evil-org-mode, i.e. `M-[hjkl]` for `org-meta*` commands.  This is mnemonic and consistent with `M-[HJKL]` for `org-shiftmeta*` as well as `[HJKL]` for `org-shift*` commands.  Also, by the nature of these commands in org-mode, they also work in different contexts, e.g. tables, dates, headings, lists.
