### ISSUE TITLE
Installation for new emacs users

### ISSUE THREAD

**Issue by kirkins** [GuiltyDolphin/org-evil#9]
Noobie question here, this is my second emacs extension _(vim user experimenting with emacs)_.

With [evil-emacs](https://github.com/emacs-evil/evil#install) I cloned the repo to `~/emacs.d` and then added the following to `~/.emacs`:

```
(add-to-list 'load-path "~/.emacs.d/evil")
(require 'evil)
(evil-mode 1)
```

Can I do something like that for `org-evil` or should I look into installing `el-get` first?

**Comment by GuiltyDolphin** [comment]
@kirkins Yes, sorry! I was considering adding installation instructions for this.

### Manual

You need to make sure you have the dependencies available (`dash`, `evil`, `monitor`).

So after you have [dash](https://github.com/magnars/dash.el), [evil](https://github.com/emacs-evil/evil), [monitor](https://github.com/GuiltyDolphin/monitor), and org-evil downloaded and placed under `.emacs.d`, you can add the following to your init file to use org-evil:

``` emacs-lisp
(add-to-list 'load-path "~/.emacs.d/evil")
(require 'evil)
(evil-mode 1)

(add-to-list 'load-path "~/.emacs.d/dash")
(require 'dash)

(add-to-list 'load-path "~/.emacs.d/monitor")
(require 'monitor)

(add-to-list 'load-path "~/.emacs.d/org-evil)
(require 'org-evil)
```

Then everything should work as expected.

### MELPA

Alternatively, if you want to install via MELPA, you can follow the instructions at http://melpa.milkbox.net/#/getting-started (or see below), then run `M-x` `package-install` `RET` `org-evil` `RET` to install the package. 

(Add the following to your init file to configure MELPA)

```emacs-lisp
(require 'package) ;; You might already have this line
(add-to-list 'package-archives
             '("melpa" . "https://melpa.org/packages/"))
(when (< emacs-major-version 24)
  ;; For important compatibility libraries like cl-lib
  (add-to-list 'package-archives '("gnu" . "http://elpa.gnu.org/packages/")))
(package-initialize) ;; You might already have this line
```

### El-get

If you decide to stick with Emacs, I would definitely recommend getting el-get, I find it a very easy way to manage packages ([example](https://github.com/GuiltyDolphin/dotfiles/blob/916e3fbd0daf6637e7bcd959bb1f2ccd7abefe52/dotfiles/emacs/custom/init.el#L50)), though you may prefer alternatives such as using raw MELPA. 

### Thanks!

I'll add manual installation instructions to the readme, thanks!
